### ISSUE TITLE
Error BOLD + HEADING

### ISSUE THREAD

**Issue by Maxence1502** [Slion/XenForoAddOnSlionsToc#6]
Hey [USER=151445]@Slion[/USER] !

Thanks for your plugin, but I have a little error.

When I put Bold + Heading 1, I got this alert :

[E_NOTICE] Array to string conversion : src/addons/Slions/Toc/BbCode.php:166

```
#0 src/addons/Slions/Toc/BbCode.php(166): XF::handlePhpError(8, '[E_NOTICE] Arra...', 's...', 166, Array)
#1 [internal function]: Slions\Toc\BbCode::handleTagH(Array, 'Bonjour+a+tous', Array, Array, Object(XF\BbCode\Renderer\SimpleHtml))
#2 src/XF/BbCode/Renderer/Html.php(307): call_user_func(Array, Array, 'Bonjour+a+tous', Array, Array, Object(XF\BbCode\Renderer\SimpleHtml))
#3 src/XF/BbCode/Traverser.php(61): XF\BbCode\Renderer\Html->renderTag(Array, Array)
#4 src/XF/BbCode/Traverser.php(37): XF\BbCode\Traverser->renderSubTree(Array, Array)
#5 src/XF/BbCode/Traverser.php(20): XF\BbCode\Traverser->renderAst(Array, Object(CMTV\Code\XF\BbCode\RuleSet), Array)
#6 src/XF/SubContainer/BbCode.php(220): XF\BbCode\Traverser->render('[H1=Bonjour+a+t...', Object(XF\BbCode\Parser), Object(CMTV\Code\XF\BbCode\RuleSet), Array)
#7 src/XF/Service/Message/Preparer.php(289): XF\SubContainer\BbCode->render('[H1=Bonjour+a+t...', 'simpleHtml', 'post:prepare', Object(NF\Discord\XF\Entity\Post))
#8 src/XF/Service/Message/Preparer.php(131): XF\Service\Message\Preparer->checkValidity('[H1=Bonjour+a+t...')
#9 src/XF/Service/Post/Preparer.php(98): XF\Service\Message\Preparer->prepare('[H1=Bonjour+a+t...', true)
#10 src/XF/Service/Post/Editor.php(127): XF\Service\Post\Preparer->setMessage('[H1=Bonjour+a+t...', true, true)
#11 src/XF/Pub/Controller/Post.php(58): XF\Service\Post\Editor->setMessage('[H1=Bonjour+a+t...')
#12 src/addons/BS/ScheduledPosting/XF/Pub/Controller/Post.php(12): XF\Pub\Controller\Post->setupPostEdit(Object(NF\Discord\XF\Entity\Post))
#13 src/addons/TickTackk/ChangeContentOwner/XF/Pub/Controller/Post.php(51): BS\ScheduledPosting\XF\Pub\Controller\Post->setupPostEdit(Object(NF\Discord\XF\Entity\Post))
#14 src/XF/Pub/Controller/Post.php(127): TickTackk\ChangeContentOwner\XF\Pub\Controller\Post->setupPostEdit(Object(NF\Discord\XF\Entity\Post))
#15 src/addons/BS/ScheduledPosting/XF/Pub/Controller/Post.php(24): XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#16 src/addons/TickTackk/ChangeContentOwner/XF/Pub/Controller/Post.php(66): BS\ScheduledPosting\XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#17 src/addons/SV/MultiPrefix/XF/Pub/Controller/Post.php(49): TickTackk\ChangeContentOwner\XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#18 src/XF/Mvc/Dispatcher.php(350): SV\MultiPrefix\XF\Pub\Controller\Post->actionEdit(Object(XF\Mvc\ParameterBag))
#19 src/XF/Mvc/Dispatcher.php(257): XF\Mvc\Dispatcher->dispatchClass('XF:Post', 'Edit', Object(XF\Mvc\RouteMatch), Object(SV\MultiPrefix\XF\Pub\Controller\Post), NULL)
#20 src/XF/Mvc/Dispatcher.php(113): XF\Mvc\Dispatcher->dispatchFromMatch(Object(XF\Mvc\RouteMatch), Object(SV\MultiPrefix\XF\Pub\Controller\Post), NULL)
#21 src/XF/Mvc/Dispatcher.php(55): XF\Mvc\Dispatcher->dispatchLoop(Object(XF\Mvc\RouteMatch))
#22 src/XF/App.php(2300): XF\Mvc\Dispatcher->run()
#23 src/XF.php(488): XF\App->run()
#24 index.php(20): XF::runApp('XF\\Pub\\App')
#25 {main}
```

```
array(4) {
  ["url"] => string(17) "/posts/10340/edit"
  ["referrer"] => string(48) "https://forum.the-programmer.com/post/test.1795/"
  ["_GET"] => array(0) {
  }
  ["_POST"] => array(9) {
    ["message_html"] => string(86) "<h1 data-id="Bonjour+a+tous"><strong>Bonjour a tous,</strong></h1><p>ds</p><p><br></p>"
    ["_xfInlineEdit"] => string(1) "1"
    ["attachment_hash"] => string(32) "bbdd4e6c4e1c100eff3f12196036a8a8"
    ["attachment_hash_combined"] => string(85) "{"type":"post","context":{"post_id":10340},"hash":"bbdd4e6c4e1c100eff3f12196036a8a8"}"
    ["username"] => string(0) ""
    ["_xfToken"] => string(8) "********"
    ["_xfRequestUri"] => string(16) "/post/test.1795/"
    ["_xfWithData"] => string(1) "1"
    ["_xfResponseType"] => string(4) "json"
  }
}
```

Can you fix it please ?

**Comment by Slion** [comment]
Thanks for reporting that issue. I could reproduce it but I'm not sure when I will have time to investigate and fix it.

**Comment by Maxence1502** [comment]
Thanks for your answer, tell me if you need more informations.
This is a fairly recurring problem, I've already had 3 reports of this problem since I installed your plugin last week

**Comment by Maxence1502** [comment]
Hey! Did you had time to check ?

**Comment by Slion** [comment]
> Hey! Did you had time to check ?

Nope, it could be a while.

**Comment by Maxence1502** [comment]
Oh okay :'(

**Comment by Maxence1502** [comment]
Up please

**Comment by Maxence1502** [comment]
Hey! Any update about this bug please ?

**Comment by Slion** [comment]
That issue seems to be different now on XenForo 2.2.13.
It still does not render correctly though.
An easy fix could be to just deactivate processing of BB codes inside headings.

**Comment by Slion** [comment]
Deactivated nested bbcodes in c2ee1f5 and 69b1b91.
